#!/usr/bin/env node
/**
 * BollaClaw Onboard CLI
 * Run: npx ts-node src/onboard/cli.ts
 * Or after build: node dist/onboard/cli.js
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { OnboardManager } from './OnboardManager';

const ENV_FILE = path.resolve(process.cwd(), '.env');
const ENV_EXAMPLE = path.resolve(process.cwd(), '.env.example');

function ask(rl: readline.Interface, question: string, defaultVal = ''): Promise<string> {
  const suffix = defaultVal ? ` [${defaultVal}]` : '';
  return new Promise((resolve) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function setupEnv(rl: readline.Interface): Promise<void> {
  if (fs.existsSync(ENV_FILE)) {
    console.log('');
    console.log('  ⚠️  Arquivo .env já existe.');
    const overwrite = await ask(rl, 'Deseja reconfigurar? (s/n)', 'n');
    if (overwrite.toLowerCase() !== 's') return;
  }

  console.log('');
  console.log('==========================================');
  console.log(' 🔑 Configuração do Ambiente (.env)');
  console.log('==========================================');
  console.log('');

  // Telegram
  const botToken = await ask(rl, 'Telegram Bot Token (do @BotFather)');
  const allowedIds = await ask(rl, 'Telegram User IDs permitidos (separados por vírgula)');

  // LLM Provider
  console.log('');
  console.log('  Provedores LLM disponíveis:');
  console.log('  1. Claude (Anthropic) — recomendado');
  console.log('  2. Gemini (Google)');
  console.log('  3. DeepSeek');
  console.log('  4. Groq');
  console.log('');
  const providerChoice = await ask(rl, 'Escolha o provedor principal (1-4)', '1');
  const providerMap: Record<string, string> = { '1': 'claude', '2': 'gemini', '3': 'deepseek', '4': 'groq' };
  const llmProvider = providerMap[providerChoice] ?? 'claude';

  // API Keys
  let anthropicKey = '';
  let geminiKey = '';
  let deepseekKey = '';
  let groqKey = '';

  console.log('');
  console.log('  Configure as API keys (ENTER para pular):');

  if (llmProvider === 'claude') {
    anthropicKey = await ask(rl, 'Anthropic API Key (obrigatório para Claude)');
  } else {
    anthropicKey = await ask(rl, 'Anthropic API Key (opcional)', '');
  }

  if (llmProvider === 'gemini') {
    geminiKey = await ask(rl, 'Gemini API Key (obrigatório para Gemini)');
  } else {
    geminiKey = await ask(rl, 'Gemini API Key (opcional)', '');
  }

  if (llmProvider === 'deepseek') {
    deepseekKey = await ask(rl, 'DeepSeek API Key (obrigatório para DeepSeek)');
  } else {
    deepseekKey = await ask(rl, 'DeepSeek API Key (opcional)', '');
  }

  // Groq is always useful (for STT + as fallback LLM)
  groqKey = await ask(rl, 'Groq API Key (usado para STT Whisper + LLM fallback)', '');

  // Admin
  console.log('');
  const adminPass = await ask(rl, 'Senha do painel Admin', 'bollaclaw');
  const adminPort = await ask(rl, 'Porta do painel Admin', '3000');

  // Build .env content
  const envContent = `# =============================================
# BollaClaw V0.1 - Environment Configuration
# Generated by onboard on ${new Date().toISOString()}
# =============================================

# --- Telegram ---
TELEGRAM_BOT_TOKEN=${botToken}
TELEGRAM_ALLOWED_USER_IDS=${allowedIds}

# --- LLM Provider ---
LLM_PROVIDER=${llmProvider}

# API Keys
ANTHROPIC_API_KEY=${anthropicKey}
GEMINI_API_KEY=${geminiKey}
DEEPSEEK_API_KEY=${deepseekKey}
GROQ_API_KEY=${groqKey}

# --- Agent Config ---
MAX_ITERATIONS=5
MEMORY_WINDOW_SIZE=20
SKILLS_DIR=.agents/skills

# --- Audio (STT/TTS) ---
STT_PROVIDER=groq_whisper
TTS_VOICE=pt-BR-ThalitaMultilingualNeural
AUTO_AUDIO_REPLY=true

# --- Admin Panel ---
ADMIN_ENABLED=true
ADMIN_PORT=${adminPort}
ADMIN_PASSWORD=${adminPass}
ADMIN_HOST=0.0.0.0

# --- Paths ---
DATA_DIR=./data
TMP_DIR=./tmp
LOGS_DIR=./logs

# --- Logging ---
LOG_LEVEL=info
`;

  fs.writeFileSync(ENV_FILE, envContent, 'utf-8');
  console.log('');
  console.log('  ✅ Arquivo .env criado com sucesso!');
}

async function main(): Promise<void> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('');
  console.log('╔══════════════════════════════════════════╗');
  console.log('║    🤖 BollaClaw V0.1 - Setup Wizard     ║');
  console.log('╠══════════════════════════════════════════╣');
  console.log('║  Este wizard vai configurar:             ║');
  console.log('║  1. Variáveis de ambiente (.env)         ║');
  console.log('║  2. Identidade do agente                 ║');
  console.log('║  3. Comportamento e regras               ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log('');

  // Step 1: Setup .env
  await setupEnv(rl);

  // Step 2: Onboard identity
  rl.close();
  const onboard = new OnboardManager();
  await onboard.runInteractiveOnboard();

  console.log('');
  console.log('╔══════════════════════════════════════════╗');
  console.log('║  🚀 Setup completo!                     ║');
  console.log('║                                         ║');
  console.log('║  Para iniciar o BollaClaw:               ║');
  console.log('║    npm run pm2:start                     ║');
  console.log('║                                         ║');
  console.log('║  Para ver logs:                          ║');
  console.log('║    npm run pm2:logs                      ║');
  console.log('║                                         ║');
  console.log('║  Painel Admin:                           ║');
  console.log('║    http://SEU_IP:3000                    ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log('');
}

main().catch((err) => {
  console.error(`❌ Erro no onboard: ${err.message}`);
  process.exit(1);
});
